language: go

go:
  - tip

before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

before_script:
  - go vet ./...
  - golint ./... | xargs -r false

script:
  - go test -v -covermode=count -coverprofile=coverage.txt ./...
  - go test -v -race ./...

after_success:
  - goveralls -service travis-ci -coverprofile coverage.txt
